Проверяем макет по критериям
htmlacademy-htmlcss/893399-sedona-32 pull request #12
Opened 2021-11-16 13:29 UTC by meledi555

2021-11-17 06:54 UTC, Dima-Dim commented
Нужно решить конфликты.
https://github.com/htmlacademy-htmlcss/893399-sedona-32/pull/12

2021-11-17 07:51 UTC, meledi555 commented
Поправила конфликты

2021-11-17 17:27 UTC, Dima-Dim requested changes
Для чего css/styles-911.css?

images/social/facebook-dark.svg ? Это делается с помощью css.

Состояния чекбоксов, радиокнопок и блока "Стоимость", кнопки "Применить" не соответствуют макету.

При фокусе на Подробнее на страницы Гостинцы контент соседних блоков двигается, а такого быть не должно.

2021-11-17 17:27 UTC, Dima-Dim commented on catalog.html
> +                        <img width="16" height="14" src="images/icons/mode-tile.svg"  alt="" />
Это же не контентыне изображения, почему они в теге img?
И за одно https://up.htmlacademy.ru/htmlcss/32/criteries#ALLY-02

2021-11-17 17:27 UTC, Dima-Dim commented on catalog.html
> +                    <p class="stars stars-4"></p>
Странный пустой тег. Похоже на https://up.htmlacademy.ru/htmlcss/32/criteries#HTML-06

2021-11-17 17:27 UTC, Dima-Dim commented on catalog.html
> +                <select class="control-select">
Точно вокруг select-а нужны две обёртки?

2021-11-18 07:48 UTC, meledi555 commented on catalog.html
> +                        <img width="16" height="14" src="images/icons/mode-tile.svg"  alt="" />
Исправлено

2021-11-18 07:48 UTC, meledi555 commented on catalog.html
> +                    <p class="stars stars-4"></p>
Исправлено

2021-11-18 07:49 UTC, meledi555 commented on catalog.html
> +                        <img width="16" height="14" src="images/icons/mode-tile.svg"  alt="" />
css/styles-911.css - удален
При фокусе на Подробнее на страницы Гостинцы контент соседних блоков двигается - исправлено

2021-11-18 07:56 UTC, meledi555 commented on catalog.html
> +                <select class="control-select">
Исправлено

2021-11-18 11:22 UTC, merged